### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by geojames** [geojames/DietrichCV#1]
# Task List for ATL24 Development
### File Reading
- [ ] Design test/checks for "bad" granules - @geojames
- [ ] Rewrite icesat2.from_h5 - @geojames 
- [ ] small function for quick Bounding box extract

**Comment by geojames** [comment]
Testting complete
